### ISSUE TITLE
use release.NugetVersion as nuget package version

### ISSUE THREAD

**Issue by blairconrad** [machine/machine.fakes#27]
Sorry to be a bother, but I was building machine.fakes with a pre-release FakeItEasy as part of my work on FakeItEasy/FakeItEasy#468 and got a build failure, which turned out to just be a problem where a stable machine.fakes nuget version (2.6.0) depended on unstable FakeItEasy 2.0.0-beta07.

Everything else passed, and I wasn't concerned, but still.

I updated `changelog.markdown` to contain a beta version, but ran into the same failure because `build.fsx` uses `release.AssemblyVersion` for the NuGet package version.
Undeterred, I checked the [Fake ReleaseNotesHelper docs](http://fsharp.github.io/FAKE/apidocs/fake-releasenoteshelper-releasenotes.html) and found the `NugetVersion` attribute, which I tried out. It worked perfectly.

Even though there's no problem now, I figure in the future you _may_ want to release a beta version, and it might be handy to have the NuGet package version-setting pick up the right version from the changelog.

**Comment by blairconrad** [comment]
Thanks!

**Comment by SimonHohenadl** [comment]
No, thank you!
