### ISSUE TITLE
Prepare for FakeItEasy 2.0

### ISSUE THREAD

**Issue by blairconrad** [machine/machine.fakes#30]
FakeItEasy 2.0.0 will bring with it a change that breaks Machine.Fakes. Specifically, `IFakeOptionsBuilder<T>` is renamed `IFakeOptions<T>`.
This will break anyone who updates the FakeItEasy version after 2.0.0 is released.

@SimonHohenadl, are you interested in preparing Machine.Fakes for this change? There's little to do for people using previous versions of Machine.Fakes, but a new release limiting the imported FakeItEasy version to be strictly less than 2.0 could be a good stopgap. Then if you were interested in depending on FakeItEasy 2.0+ in a subsequent release I'd be happy to submit a PR to update the Machine.Fakes code.

**Comment by SimonHohenadl** [comment]
Thanks for thinking of Machine.Fakes!
Unfortunately, I am not really maintaining it any more. I don't even have a working development environment at the moment. I have been trying to find someone to take over - without success.

**Comment by blairconrad** [comment]
Ah. That is quite sad. I'd offer, but I have enough side projects right now. Worse, I don't even use the product, and I find that's quite a barrier to being an active contributor, let alone owner/maintainer.
I'm not sure what to do here. :frowning:
With so many downloads on NuGet, I would've thought somebody would be interested. Ah well.

Regardless, if you (or a future owner, if any show up) end up wanting some work done to fix the FakeItEasy integration, my offer of PRs still stands. Just alert me.

**Comment by adamralph** [comment]
For the time being, we'll remove this project from our [2.0.0 checklist](https://github.com/FakeItEasy/FakeItEasy/issues/336).

**Comment by SimonHohenadl** [comment]
Fair enough.

**Comment by adamralph** [comment]
Curiosity got the better of me. The fix turned out to be trivial that, FWIW, I raised a PR - https://github.com/machine/machine.fakes/issues/31
