### ISSUE TITLE
Check compatibility with FakeItEasy 3.0.0

### ISSUE THREAD

**Issue by adamralph** [machine/machine.fakes#37]
FakeItEasy 3.0.0 [is due very soon](https://github.com/FakeItEasy/FakeItEasy/issues/902).

I attempted to check this myself by changing the dependency in the `project.json` to `"FakeItEasy": "3.0.0-rc001-build000097"` and running `build.ps1`. I received this as an output:

```
Running tests...
All good!
```

But the "All good!" message appears almost instantaneously, so I'm sceptical about whether any tests are actually being run.

I also considered swapping out the FakeItEasy.dll and running the tests, but I'm not sure what's required to run the specs from Visual Studio, and whatever it is, I don't possess it.

**Comment by ivanz** [comment]
Hm. Try `build-local.bat`. However heads up that the tests for FakeItEasy (namespace `Machine.Fakes.Adapters.Specs.FakeItEasy`) when targeting .Net Standard are currently hidden behind "#if !NETSTANDARD"

**Comment by ivanz** [comment]
I've pulled in the latest version of FakeItEasy and ran the tests. Going to release machine fakes 2.8.0 in a moment with the support for it.

**Comment by adamralph** [comment]
Thanks for the update @ivanz
