### ISSUE TITLE
Machine.Fakes.FakeItEasy Source-incompatible with FakeItEasy 3.3.0+

### ISSUE THREAD

**Issue by blairconrad** [machine/machine.fakes#40]
From https://github.com/FakeItEasy/FakeItEasy/issues/1117#issuecomment-317392975.

Machines.Fakes.FakeItEasy has some source-level incompatibilities with FakeItEasy. Four unit tests fail, with 2 different errors:

```
System.ArgumentException: GenericArguments[0], 'System.String', on 'System.Nullable`1[T] IsNull[T](FakeItEasy.IArgumentConstraintManager`1[System.Nullable`1[T]])' violates the constraint of type 'T'. ---> System.Security.VerificationException: Method FakeItEasy.ArgumentConstraintManagerExtensions.IsNull: type argument 'System.String' violates the constraint of type parameter 'T'.
```

occurs when we try to translate `Param<String>.IsNull` into `A<T>.That.IsNull` and find the overload for a nullable struct instead of a class. (The former was added to FakeItEasy 3.3.0 in issue #1062.)

Also:
```
System.InvalidOperationException: Unable to find target property Not on instance of target type FakeItEasy.IArgumentConstraintManager`1[[System.String, System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]]
```

similarly occurs when Machine.Fakes tries to translate a `Param<String>.IsNotNull`. FakeItEasy is moving `Not` to a different interface with the  4.0.0 release, in #1063. (And have added `IsNotNull`, which would save Machine.Fakes.FakeItEasy a step, in 3.3.0 - #1062 again).

If you're interested in resolving these issues, I'm happy to, either together or in two PRs.
If you'd like me to work on them, would you prefer to continue to support FakeItEasy 3.1.0+ in the next release of Machine.Fakes, or do you prefer to restrict clients to using FakeItEasy 4.0.0+?

**Comment by ivanz** [comment]
Hey and sorry for the delayed response here. It's would be pretty awesome if you can send PRs this way :)

**Comment by blairconrad** [comment]
Sure. I can take a look. Before I get started, which approach do you prefer?

> to continue to support FakeItEasy 3.1.0+ in the next release of Machine.Fakes, or do you prefer to restrict clients to using FakeItEasy 4.0.0+?

It's likely that either's achievable, but the former would require some reflection, making for slightly less efficient (and harder to maintain) code. Nothing terrible, but if you have no interest in supporting < 4.0.0, I might as well take the easy way out.

**Comment by ivanz** [comment]
I reckon it should be fine to just target 4.x and do a major version bump of this lib.

**Comment by blairconrad** [comment]
Fair enough. I'm traveling for a week, but will pick this up after I get
home.

**Comment by blairconrad** [comment]
We already reference FakeItEasy 4.0.0, since @robertcoltheart's #41 has been merged.
The tests are no longer being run, though. At least my local build does not run them:

```
Test run for D:\Sandbox\machine.fakes\Source\Machine.Fakes.Specs\bin\Debug\net45\Machine.Fakes.Specs.dll(.NETFramework,Version=v4.5)
Microsoft (R) Test Execution Command Line Tool Version 15.0.0.0
Copyright (c) Microsoft Corporation.  All rights reserved.

The path 'D:\Sandbox\machine.fakes\Source\Machine.Fakes.Specs\bin\Debug\net45' specified in the 'TestAdapterPath' does not contain any test adapters, provide a valid path and try again.

Starting test execution, please wait...
No test discoverer is registered to perform discovery of test cases. Register a test discoverer and try again
```

(If they were run, I'd expect there would be failures.)

I can't find the AppVeyor project to compare against.

Am I  mistaken, and are the specs being run somehow? Alternatively, is there a plan to re-enable?

**Comment by robertcoltheart** [comment]
I don't think this PR has been released to Nuget yet, so presumably your tests won't work until this is done. @ivanz do you have any further issues to get in before creating a release?

**Comment by blairconrad** [comment]
Thanks for the response, @robertcoltheart. I may not have made my steps clear, but I'm testing from within the repo. That is, I updated my clone and then tried to build. That's when the problems started.

I found [Building Machine.Fakes from source](https://github.com/machine/machine.fakes#building-machinefakes-from-source) to be no help, but I ran `build.ps1` when I found no `build.cmd`.

It fails quickly with 
```
Restoring packages...
error: Invalid input 'Source\Machine.Fakes.sln'. The file type was not recognized.
```
but I was going to report that separately.

Then I updated `global.json` to use SDK 2.0.0 (or 1.0.3 - same result). After that `build.ps1` reports no problems, but as you can see from the output I pasted above, no tests are detected.

This is part of the reason I was hoping to see the AppVeyor project. I figured I could see what the differences are between my environment and its, and not have to bother people. (Like I'm doing now!)

When you submitted your PR, how did you build and run the tests?

**Comment by robertcoltheart** [comment]
Hm, you're right. I'll have to take a look at this later tonight. Definitely part of the problem is the `global.jon` which should be updated. I suspect there is still some lingering config somewhere that is messing with the build process.

**Comment by robertcoltheart** [comment]
@ivanz Just a heads up, I've found multiple issues that will need to be resolved, please don't release what's in master as it is most likely broken! 😢

**Comment by robertcoltheart** [comment]
@blairconrad please take a look at #42. Fixes some issues that were overlooked with FakeItEasy, and (I think?) fixes the local build issue. It works for me as is on Win 10 (finds the tests and runs them). I will try tomorrow on a Win 7 machine to see if it works there too.

**Comment by blairconrad** [comment]
@robertcoltheart, eyeballing the changes, I think you'll probably be good. I'm on a Win 7 machine right now. I installed the 2.0.0 SDK and ran `build.ps1`. Success. And tests are reported!

**Comment by blairconrad** [comment]
Thanks for your efforts, @robertcoltheart. I think with the merge of #42, this issue is now redundant. Closing.

**Comment by robertcoltheart** [comment]
Thanks for spotting this @blairconrad!
