### ISSUE TITLE
Update to latest version of FakeItEasy

### ISSUE THREAD

**Issue by jdeboer-geoplan** [machine/machine.fakes#47]
Hi, 
I think this is still using FakeItEasy v4.1.0 it's now on v4.9.1, is there a way to change the version of FakeItEasy it uses?

particularly want this because of https://github.com/FakeItEasy/FakeItEasy/issues/1345

Thanks.

**Comment by robertcoltheart** [comment]
I've raised a PR with the upgrade. Will test around with it a bit before we decide to merge.
